[env:m5stack-stickc-plus2]
; 强制使用官方推荐的稳定版本
platform = espressif32@6.7.0
board = m5stick-c
framework = arduino

; 烧录与调试设置
upload_speed = 1500000
monitor_speed = 115200
; 锁定我们搞定的那个 COM11
upload_port = COM11

; 开启 2MB PSRAM, 自定义分区表
board_build.partitions = partitions.csv
build_flags =
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
    -DCORE_DEBUG_LEVEL=3

; M5Unified 全家桶 — 屏幕驱动(M5GFX)、电源管理、RTC等
lib_deps =
    M5Unified=https://github.com/m5stack/M5Unified
    WebServer
    DNSServer